--- 
  bugzilla: "https://devsrv1.wohnfinder.de/bugzilla/show_bug.cgi?id="
  dropbox: c:/Users/t.fiedler/Dropbox/weekly/
  posts_directory: ../weekly-reports/_posts/
  repos: 
    svn:
      - 'svn://devsrv1/Fiomarket/IntranetOffice/IntranetOfficeFileManager' 
      - 'svn://devsrv1/Common/VacationPlanner'
      - 'svn://devsrv1/Fiomarket/Rechnungssoftware/Rechnungssoftware/branches/BRANCH_ReSo_NH_2012' 
      - 'svn://devsrv1/Fiomarket/IntranetOffice/IntranetOfficeModules'
    git:
      - c:/Users/t.fiedler/test/conversion-tools
      - c:/Users/t.fiedler/gitlab-ci-deploy/scripts
  users: 
      - t.fiedler