--- 
- 
  bugzilla: "https://example.com/?bug="
  dropbox: /optional_path/to/backup_folder
  posts_directory: ../weekly-reports/_posts/
  repos: 
    - 'svn://foo.bar/project1' 
    - 'svn://foo.bar/project2'
    - 'local/path/to/svn_repo'
  users: svn.user1
- 
  bugzilla: "https://example.com/?bug="
  posts_directory: ../weekly-reports/_posts/
  repos: 
    - 'svn://foo.bar/project1' 
    - 'svn://foo.bar/project2'
    - 'local/path/to/svn_repo'
  users: svn.user2